### PR TITLE
Find user from prof

### PR DESCRIPTION
**Pull request by JonahLandry**
Worked with Dario, Cole, and Tommy in order to get the ability to follow other users from their profile functional on front and back end!

### CODE REVIEW

**Comment by dariorobinson** [comment]
Great job guys!

**Review by dariorobinson — APPROVED** [review]
Great job guys!

**Review by CrypticCapybara — APPROVED** [review]
Awesome

**Review by Dragonimi — APPROVED** [review]
Most merge conflicts were 1 liners with moved curly braces. Easy to fix.

SQL file changed extensively. Everyone should update.

**Pull request merged**
